### PR TITLE
fixed indentation issue.

### PR DESCRIPTION
**Pull request by ozylol**

### CODE REVIEW

**Comment by cxdy** [comment]
Thanks.

**Comment by cxdy** [comment]
This can't be merged if you close it. Are you revoking your request?

**Comment by ozylol** [comment]
Well when I tried to run the script, it gave me an error with the if
statements. So you might want to check that out. Also use raw_input instead
input and change to values from 1 to '1'. Worked better for me when I did
it that way. Last one, if you change the while loop to a for statement, you
can get user input on how many threads you would like to send to user. Just
some critics to make the script a bit better. :)

**Comment by cxdy** [comment]
I am using raw_input, but not on the password field because otherwise it's not hidden. I definitely will add the ability to choose the amount of emails though.

**Comment by ozylol** [comment]
Hi Cody, I currently just finished up my first version of Disrupt found here: https://github.com/ozylol/disrupt <https://github.com/ozylol/disrupt>. I gave you credit if you read it. The idea of the first module obviously came from you, so I just made a fairly different version of it. If you want to contribute to the repository please do.

Regards, Matt.

**Comment by cxdy** [comment]
Hey, my comment didn't post for some reason but it looks fantastic. Nice work. If I have anything to contribute, I definitely will.

**Pull request closed without merging**
